### ISSUE TITLE
suggestion - mobs too

### ISSUE THREAD

**Issue by superon** [Trikzon/Sneak-Through-Berries#14]
i'd like to see the behaviour extended to include mobs as well as players

**Comment by Trikzon** [comment]
How? Mobs can't sneak and it wouldn't make sense for mobs to never take damage from sweet berries

**Comment by superon** [comment]
in a forest filled with sweet berry bushes destroying any pig before you can ride it it makes sense... sneaking is besides the point as there's an option in the config "sneakToStopDamage"..   or is that option literally disabling the mod ? :/

**Comment by Trikzon** [comment]
Tbh, the config for this mod is in a really really bad state. I need to rethink it for when I port it to 1.17.1 and 1.18.1 soon.

Disabling `sneakToStopDamage` disables the sneaking part of the mod. It doesn't disable the part where wearing some armor (depending on the config) will also prevent damage.

I guess the wearing armor thing could be done for mobs instead of just players now that I think of it.

But I don't plan on making any changes to 1.16.5 or before. Any changes will be in 1.17.1 and 1.18.1

**Comment by superon** [comment]
well, as i believe in options being a good thing i still suggest the option to have this available: mob wearing armor should also be optional.
i understand many authors have now given up on updating for anything older than 1.18.   i'm still creating a pack for 1.16 but think this option would be good for people other than myself

**Comment by Trikzon** [comment]
Closed without adding this suggestion because it's out of scope of the mod
