### ISSUE TITLE
[Bug] Settings aren't working as expected

### ISSUE THREAD

**Issue by supersaiyansubtlety** [Trikzon/Sneak-Through-Berries#7]
When using these settings:
```
{
  "requireBootsToWalk": false,
  "requireLeggingsToWalk": false,
  "requireChestToWalk": false,
  "requireHelmetToWalk": false,
  "requireNothingToWalk": false,
  "worksForPlayer": true,
  "worksForNonPlayer": true
}
```
I get the following behavior:
- While wearing no armor I take no damage from berries, sneaking or not. 
- While wearing any armor, I take damage from berries while not sneaking, and none while sneaking. 

This doesn't seem right. With these settings I'd expect to always take damage when not sneaking and never take damage when sneaking, regardless of armor. 

The settings could also use a bit more explanation. It's not clear whether `"requireBootsToWalk": true` means wearing boots lets you avoid damage even while sneaking or if it means you must both sneak and wear boots to avoid damage.

**Comment by Trikzon** [comment]
I swear, these configs will be the end of me :p

The problem is that the current system totals up the number of armor required and if the player is wearing that much you can walk.
This is a stupid system that I rushed out and didn't test much, sorry about that.

Two problems with it is that
1. You require the exact amount of armor because it is using the `==` operator instead of `>=`.
2. If the config has 0 armor selected it will let you walk without any armor.

I'll fix this config system sometime in the next few days.

---

Also, I think the `requireBootsToWalk` is descriptive enough, at least the best I can do for a json key, if it performed currectly.
It is meant to mean that if it is true and you wear boots you can walk through the berries without taking any damage.

**Comment by supersaiyansubtlety** [comment]
Ok, sounds good. 
As for the config clarity, you could use json5 which allows comments, or you could just have dummy pairs like
```
{
  "note": "This is an in-depth explanation for shortSettingName!",
  "shortSettingName": true
}
```

**Comment by Trikzon** [comment]
I've simplified the config options and made them work properly in the latest release. (v1.1.0)
Expect it to be out shortly
